# Generated by Django 5.1.2 on 2024-10-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
